{{- if .Values.privateRegistry.secret }}
{{- $imagePullSecret := printf "{\"auths\":{\"%s\": {\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.privateRegistry.url .Values.privateRegistry.username .Values.privateRegistry.password | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{$imagePullSecret}}
{{- end }}