{{- if .Values.global.tls.enabled }}
{{- if and .Values.global.tls.caKey .Values.global.tls.caKey.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tls.caKey.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: "guide-rails-cert-management"
type: Opaque
data:
  tls.key: {{ .Values.global.tls.caKey.key | b64enc }}
{{- end }}
{{- end }}
