{{- if .Values.global.tls.enabled }}
{{- if .Values.global.tls.caKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tls.caKey.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.key: {{ .Values.global.tls.caKey.key | b64enc }}
{{- end }}
{{- end }}
